// ============================================================
// 用户提供的专业知识库 — Triphasic训练、Tuck Jump评估、弹跳专项诊断
// ============================================================

export interface KBEntry {
  id: string;
  type: "weakness_diagnosis" | "exercise" | "periodization_rule";
  condition: string;
  diagnosis?: string | null;
  target?: string | null;
  name?: string | null;
  equipment?: string | null;
  difficulty?: string | null;
  contraindications?: (string | null)[] | null;
  sets_reps?: string | null;
  rationale: string;
  phase?: string | null;
  duration_weeks?: string | null;
  weekly_frequency?: string | null;
  daily_structure?: (string | null)[] | null;
}

// ================================================================
// Part 1: Triphasic Training 知识
// ================================================================
const KB_PART1: KBEntry[] = [
  {
    id: "WEAK_001", type: "weakness_diagnosis",
    condition: "运动员力-时曲线呈浅V形；发力率低；吸收力量的能力低于产生力量的能力",
    diagnosis: "离心力量不足（Eccentric weakness）。无法快速吸收高力量，限制了牵张反射和随后的向心爆发力",
    target: "反应力量",
    name: "离心专项训练（如慢速离心深蹲）",
    equipment: "杠铃、深蹲架、保护者",
    difficulty: "中级",
    contraindications: ["负荷>85% 1RM时不要做6秒以上的慢速离心——受伤风险极高", "不要在早期训练阶段对小肌群单关节动作做慢速离心"],
    sets_reps: "1-3次，2-4组",
    rationale: "增强牵张反射并降低高尔基腱器(GTO)敏感度，允许更大的弹性能储存和更高的向心阶段力量产出",
    phase: "高力低速阶段（>80% 1RM）",
    duration_weeks: "2-3",
    weekly_frequency: "2-3",
    daily_structure: ["周一（中等强度），周五（高训练量）"],
  },
  {
    id: "WEAK_002", type: "weakness_diagnosis",
    condition: "缓冲期过长（离心到向心转换慢）；能量传递效率低；力-时曲线底部可见暂停或凹陷",
    diagnosis: "等长力量不足（Isometric weakness）。无法快速减速并立即重新加速，导致能量以热量形式损失",
    target: "核心/爆发力",
    name: "等长专项训练（如暂停深蹲、暂停卧推）",
    equipment: "杠铃、深蹲架、卧推架、保护者",
    difficulty: "中级",
    contraindications: [],
    sets_reps: "1-3次，3-5组（高负荷）；3-4组，4-5次（中等负荷）",
    rationale: "教会神经肌肉系统瞬间停止离心动量并快速建立肌内张力，最大化SSC弹性储能向向心阶段的传递",
    phase: "高力低速阶段（>80% 1RM）",
    duration_weeks: "2-3",
    weekly_frequency: "2-3",
    daily_structure: ["周一（中等强度），周五（高训练量）"],
  },
  {
    id: "WEAK_003", type: "weakness_diagnosis",
    condition: "运动员力量强但速度慢；高1RM未转化为弹道动作（如垂直跳、冲刺）中的高功率输出",
    diagnosis: "发力率(RFD)不足/力量转化不足。力量增长未有效转移到高速运动中",
    target: "爆发力",
    name: "高速力量训练（如跳蹲、轻负荷奥林匹克举）",
    equipment: "杠铃、配重片、缓冲片",
    difficulty: "高级",
    contraindications: [],
    sets_reps: "1-3次，3-5组",
    rationale: "通过最大化SSC贡献训练神经系统在高速下产生高力量，将力-速曲线向右上方推移",
    phase: "高速峰值阶段（<55% 1RM）",
    duration_weeks: "3-5",
    weekly_frequency: "2-3",
    daily_structure: ["周一（理想时间），周三（低于理想时间）"],
  },
  {
    id: "EX_001", type: "exercise",
    condition: "当主要训练目标是提升下肢离心力量和反应能力，处于>80%阶段",
    target: "反应力量",
    name: "杠铃后蹲（离心专项/Triphasic）",
    equipment: "杠铃、深蹲架、保护者",
    difficulty: "中级",
    contraindications: ["5-6秒离心节奏时不要超过85% 1RM", "因高神经疲劳，始终使用保护者"],
    sets_reps: "1-3次，2-4组",
    rationale: "慢速控制离心(5-6秒)最大化肌梭刺激和GTO脱敏，增强牵张反射和弹性能储存，使向心收缩更具爆发力",
    phase: "高力低速阶段（>80% 1RM）",
    duration_weeks: "2-3",
    weekly_frequency: "1-2",
    daily_structure: ["周一（中等强度）"],
  },
  {
    id: "EX_002", type: "exercise",
    condition: "在峰值阶段（<55%）发展专项速度和爆发力",
    target: "爆发力",
    name: "卧推抛起（Bench Press Throw）",
    equipment: "史密斯机或卧推架+保护者、杠铃（轻负荷25-55% 1RM）",
    difficulty: "高级",
    contraindications: ["未经充分热身和足够训练年限不应进行", "仅使用可以安全接住或减速的次最大负荷"],
    sets_reps: "3-6次，3-5组",
    rationale: "教会运动员在整个ROM中加速杠铃不减速，最大化功率输出，训练拮抗肌快速放松（交互抑制）",
    phase: "高速峰值阶段（<55% 1RM）",
    duration_weeks: "3-5",
    weekly_frequency: "1-2",
    daily_structure: ["周三（高强度/低于理想时间）"],
  },
  {
    id: "EX_003", type: "exercise",
    condition: "休赛期需要提升一般体能(GPP)、肌肉横截面积和工作能力",
    target: "力量",
    name: "健美式肌肥大训练（如腿举）",
    equipment: "腿举机、各种器械和哑铃",
    difficulty: "初级",
    contraindications: ["赛季中不推荐高训练量（如4组×15次）——可能导致过度疲劳和酸痛"],
    sets_reps: "3-5组，10-20次",
    rationale: "中低负荷高训练量创造显著代谢压力和肌肉损伤，刺激肌肉蛋白合成和肌肥大，为未来力量和爆发力发展奠定基础",
    phase: "高力低速阶段——周五",
    duration_weeks: "2-3",
    weekly_frequency: "1-2",
    daily_structure: ["周五（低强度/高训练量）"],
  },
  {
    id: "PERIOD_001", type: "periodization_rule",
    condition: "力量、爆发力和速度周期化训练的一般指南",
    target: "力量/爆发力",
    name: "改良波浪周期化（板块系统）",
    rationale: "每周波浪化强度（周一82-87%、周三90-97%、周五75-80%），将高训练量放在周末，允许72小时恢复后进入下一周，防止自然运动员过度疲劳和训练过度",
    phase: "大周期",
    duration_weeks: "视情况（如12-20周休赛期）",
    weekly_frequency: "3-6",
    daily_structure: ["周一：全身（高力量，中训练量）", "周二：休息或上肢", "周三：全身（高强度，低训练量）", "周四：休息或下肢", "周五：全身（低强度，高训练量）", "周六：休息或专项"],
  },
  {
    id: "PERIOD_002", type: "periodization_rule",
    condition: "单一明显赛季的运动（如橄榄球、冰球）",
    target: "力量/爆发力",
    name: "线性板块递进（Triphasic）",
    difficulty: "中级/高级",
    rationale: "休赛期大周期分为三个中周期：1) 高力低速(>80% 1RM)——离心/等长/向心各2-3周，2) 高力高速(55-80% 1RM) 3-4周，3) 高速峰值(<55% 1RM) 3-5周。顺序专项化先发展力量、再爆发力、最后速度，确保所有素质在赛季达到峰值",
    phase: "休赛期大周期",
    duration_weeks: "12-20",
    weekly_frequency: "3-6",
    daily_structure: ["阶段1：周一(82-87%/Triphasic)、周三(90-97%/反应)、周五(75-80%/Triphasic)", "阶段2：周一(62-70%/Biometric)、周三(72-80%/Dynamic)、周五(55-62%/Volume)", "阶段3：周一(35-40%/AFSM)、周三(45-55%/AFSM)、周五(25-30%/AFSM)"],
  },
  {
    id: "PERIOD_003", type: "periodization_rule",
    condition: "在'高力低速'中周期内确保持续适应并针对SSC不同方面",
    target: "力量/反应力量",
    name: "板块排序（离心→等长→向心）",
    difficulty: "中级",
    rationale: "每个板块(2-3周)聚焦于三相肌肉动作的一个阶段。板块1强调离心（慢节奏），板块2强调等长（暂停），板块3强调向心（反应性爆发动作）。顺序专项化确保没有弱链，形成更窄的力-时曲线V形和更大的整体功率输出",
    phase: "高力低速阶段（>80% 1RM）",
    duration_weeks: "6-9（每板块2-3周）",
    weekly_frequency: "3",
    daily_structure: ["板块1(离心)：周一(离心深蹲)、周三(反应深蹲)、周五(离心深蹲)", "板块2(等长)：周一(等长深蹲)、周三(反应深蹲)、周五(等长深蹲)", "板块3(向心)：周一(反应深蹲)、周三(反应深蹲)、周五(反应深蹲)"],
  },
];

// ================================================================
// Part 2: Tuck Jump 评估 + 综合训练知识
// ================================================================
const KB_PART2: KBEntry[] = [
  {
    id: "wdiag_001", type: "weakness_diagnosis",
    condition: "运动员在tuck jump测试中落地时膝盖外翻（valgus），表现出韧带主导模式",
    diagnosis: "韧带主导：动态稳定性不足，膝关节过度依赖韧带而非肌肉控制，增加ACL损伤风险",
    target: "力量/核心",
    name: "tuck jump 评估",
    contraindications: ["膝关节急性损伤", "ACL重建术后早期"],
    sets_reps: "连续跳10秒，记录缺陷数量",
    rationale: "韧带主导的落地力学异常与ACL损伤风险增加相关，可通过靶向训练改善",
  },
  {
    id: "wdiag_002", type: "weakness_diagnosis",
    condition: "运动员落地时膝关节接近完全伸直，足跟着地发出响声，表现为股四头肌主导",
    diagnosis: "股四头肌主导：腘绳肌相对力量不足，无法充分缓冲落地冲击",
    target: "力量/爆发力",
    name: "tuck jump 评估",
    contraindications: ["髌腱炎", "膝关节骨关节炎"],
    sets_reps: "连续跳10秒，观察膝关节屈曲角度",
    rationale: "小膝关节屈曲角落地增加ACL和髌股关节负荷，需强化后链肌群",
  },
  {
    id: "wdiag_003", type: "weakness_diagnosis",
    condition: "运动员跳跃时双腿不对称（一侧大腿抬高明显不足或落地时间不一致）",
    diagnosis: "腿主导：双侧力量和神经肌肉控制不平衡，增加单侧损伤风险",
    target: "力量/爆发力",
    name: "tuck jump 评估",
    contraindications: ["单侧下肢手术未恢复", "严重肌力不平衡未矫正"],
    sets_reps: "连续跳10秒，观察左右对称性",
    rationale: "侧向差异是损伤风险预测因子，需通过单侧训练纠正",
  },
  {
    id: "wdiag_004", type: "weakness_diagnosis",
    condition: "运动员跳跃时躯干明显侧倾或前后摇晃，落地位置不固定",
    diagnosis: "核心功能障碍：躯干与髋关节稳定肌群控制不足，导致力量传递效率下降",
    target: "核心/反应力量",
    name: "tuck jump 评估",
    contraindications: ["腰椎间盘突出急性期", "严重下背痛"],
    sets_reps: "连续跳10秒，观察躯干控制",
    rationale: "核心控制缺陷增加膝关节负荷，影响运动表现和损伤风险",
  },
  {
    id: "exercise_001", type: "exercise",
    condition: "需要发展下肢爆发力和反应力量，适用于中级及以上运动员",
    target: "爆发力/反应力量",
    name: "深度跳 (Depth Jump)",
    equipment: "跳箱（高度根据能力12-42英寸）",
    difficulty: "高级",
    contraindications: ["膝关节或踝关节伤病未愈", "缺乏基础力量（无法深蹲1.5倍体重）", "初学者"],
    sets_reps: "3-5组，每组5-10次，组间休息2-3分钟",
    rationale: "深度跳利用拉伸-缩短循环（SSC）最大程度激活快速肌纤维和肌腱弹性，提升垂直爆发力",
    phase: "准备期后期/赛前期",
    weekly_frequency: "1-2次/周",
  },
  {
    id: "exercise_002", type: "exercise",
    condition: "发展下肢基础爆发力和跳跃能力，适用于初级运动员",
    target: "爆发力/力量",
    name: "蹲跳 (Squat Jump)",
    equipment: "无（或轻负重）",
    difficulty: "初级",
    contraindications: ["髌骨软化症", "膝盖疼痛"],
    sets_reps: "3-4组，每组6-8次，组间休息1-2分钟",
    rationale: "离心加载后立即向心起跳，强化SSC效率，是plyometric基础动作",
    phase: "一般准备期",
    weekly_frequency: "2次/周",
  },
  {
    id: "exercise_003", type: "exercise",
    condition: "发展上肢爆发力，适用于摔跤、体操、篮球等项目",
    target: "爆发力",
    name: "俯卧撑抛起 (Plyometric Push-up)",
    equipment: "软垫",
    difficulty: "高级",
    contraindications: ["肩袖损伤", "腕管综合征", "胸锁关节不稳"],
    sets_reps: "3-5组，每组5-8次，组间休息1-2分钟",
    rationale: "通过快速离心-向心转换，增强上肢推的爆发力和肩部稳定肌群反应",
    phase: "赛前期",
    weekly_frequency: "1-2次/周",
  },
  {
    id: "exercise_004", type: "exercise",
    condition: "发展核心稳定性和髋部控制，适用于所有运动员（尤其是女性预防ACL损伤）",
    target: "核心/恢复",
    name: "单腿骨盆桥 (Single-Leg Pelvic Bridge on BOSU)",
    equipment: "BOSU球",
    difficulty: "中级",
    contraindications: ["下背痛急性期", "骶髂关节功能障碍"],
    sets_reps: "每侧10次，2-3组，组间休息30秒",
    rationale: "在不稳定平面进行单腿桥式，增强臀肌和核心控制，改善动态平衡，降低ACL风险",
    phase: "准备期/康复期",
    weekly_frequency: "2-3次/周",
  },
  {
    id: "exercise_005", type: "exercise",
    condition: "发展小腿弹性力量和反应速度，适用于短跑、跳跃项目",
    target: "反应力量",
    name: "双脚踝跳 (Two-Foot Ankle Hop)",
    equipment: "无",
    difficulty: "初级",
    contraindications: ["跟腱炎", "足底筋膜炎急性期"],
    sets_reps: "3组，每组20次，连续跳跃，组间休息45秒",
    rationale: "仅靠踝关节屈伸产生弹性力量，强化跟腱和足底筋膜储存-释放能量的能力",
    phase: "准备期",
    weekly_frequency: "2-3次/周",
  },
  {
    id: "exercise_006", type: "exercise",
    condition: "发展水平方向的爆发力和单腿稳定能力，适用于足球、篮球等项目",
    target: "爆发力/反应力量",
    name: "单腿侧向跳 (Single-Leg Lateral Jump)",
    equipment: "小障碍物（可选）",
    difficulty: "中级",
    contraindications: ["踝关节扭伤恢复期", "膝关节外侧疼痛"],
    sets_reps: "每侧3-4组，每组6-8次，组间休息90秒",
    rationale: "模拟运动中侧向变向动作，提升单腿侧向弹跳能力和落地控制",
    phase: "赛前期/比赛期",
    weekly_frequency: "1-2次/周",
  },
  {
    id: "exercise_007", type: "exercise",
    condition: "发展躯干旋转力量和核心爆发力，适用于棒球、网球等旋转运动",
    target: "核心/爆发力",
    name: "俄罗斯转体 (Russian Twist)",
    equipment: "药球",
    difficulty: "中级",
    contraindications: ["腰椎间盘突出", "腹直肌分离"],
    sets_reps: "2-3组，每组每侧10-15次，组间休息45秒",
    rationale: "动态旋转强化腹斜肌和旋转稳定性，改善挥杆、投掷等爆发力输出",
    phase: "准备期/赛前期",
    weekly_frequency: "2-3次/周",
  },
  {
    id: "exercise_008", type: "exercise",
    condition: "康复后期评估运动员是否具备返回运动能力",
    target: "恢复",
    name: "单腿跳跃距离测试（单跳、交叉跳、三级跳）",
    equipment: "卷尺、标记线",
    difficulty: "中级",
    contraindications: ["术后未满6个月", "修复侧肢体力量<健侧90%"],
    sets_reps: "每条腿3次尝试，取最大值",
    rationale: "单腿跳跃距离能有效识别肢体间力量、爆发力和控制不对称，返回运动标准为患侧≥健侧90%",
    phase: "康复末期/返回运动前",
  },
  {
    id: "exercise_009", type: "exercise",
    condition: "发展髋关节稳定性和单腿离心力量，适用于跑跳运动员",
    target: "力量/核心",
    name: "单腿深蹲 (Single-Leg Squat)",
    equipment: "箱或平台（12-24英寸高）",
    difficulty: "中级",
    contraindications: ["膝关节骨关节炎晚期", "半月板撕裂未经修复"],
    sets_reps: "3-4组，每组每侧6-8次，慢速控制（8-2-2节奏）",
    rationale: "离心控制下蹲强化腘绳肌和臀肌，改善膝外翻控制，预防ACL损伤",
    phase: "准备期/康复期",
    weekly_frequency: "2-3次/周",
  },
  {
    id: "exercise_010", type: "exercise",
    condition: "发展最大力量和髋关节稳定性，适用于所有力量训练者",
    target: "力量",
    name: "杠铃深蹲 (Barbell Back Squat)",
    equipment: "杠铃、深蹲架",
    difficulty: "初级（需指导）",
    contraindications: ["腰椎间盘突出急性期", "SI关节功能障碍", "髌股关节疼痛综合征（需调整深度）"],
    sets_reps: "3-5组，3-6次，75-85%1RM（最大力量期）",
    rationale: "深蹲是发展下肢最大力量和核心稳定性的基础动作，与短跑、跳跃、力量举表现高度相关",
    phase: "最大力量期",
    weekly_frequency: "2-3次/周",
  },
  {
    id: "exercise_011", type: "exercise",
    condition: "发展全身爆发力和功率输出，适用于几乎所有运动员",
    target: "爆发力",
    name: "高翻 (Power Clean)",
    equipment: "杠铃、缓冲片",
    difficulty: "高级",
    contraindications: ["手腕、肘或肩关节不稳定", "腰背损伤", "技术未经正确指导"],
    sets_reps: "3-6组，每组2-4次，60-80%1RM",
    rationale: "高翻涉及下肢三关节伸展和上肢快速提拉，是提高全身爆发力最有效的动作之一，与冲刺、跳跃高度显著相关",
    phase: "赛前期/转换期",
    weekly_frequency: "2-3次/周",
  },
  {
    id: "exercise_012", type: "exercise",
    condition: "发展腘绳肌离心力量和预防腿后侧拉伤",
    target: "力量/反应力量",
    name: "俄罗斯腘绳肌弯举 (Russian Hamstring Curl)",
    equipment: "训练搭档或固定带",
    difficulty: "中级",
    contraindications: ["腘绳肌拉伤急性期", "腰背痛"],
    sets_reps: "3-4组，每组5-8次，离心阶段3-5秒",
    rationale: "强化腘绳肌离心力量可显著降低腿后侧拉伤风险，提高冲刺和变向能力",
    phase: "准备期",
    weekly_frequency: "2次/周",
  },
  {
    id: "periodization_001", type: "periodization_rule",
    condition: "赛季前减量阶段，为重要比赛做准备",
    name: "指数型减量 (Exponential Taper)",
    rationale: "指数型减量（快衰减）相比线性减量能带来更大性能提升（约4-5%），优于阶梯减量（1.2-1.5%）",
    phase: "比赛期前/减量期",
    duration_weeks: "1-4周（最佳8-14天）",
    weekly_frequency: "维持训练频率为减量前的80%以上",
    daily_structure: ["减少训练量41-60%", "维持或略微提高训练强度", "采用非线性、指数型减少训练负荷"],
  },
  {
    id: "periodization_002", type: "periodization_rule",
    condition: "准备期采用阶梯加载模式，适用于中级运动员",
    name: "3:1加载模式",
    rationale: "3周递增负荷后接1周减量，能有效管理疲劳并促进超补偿，是经典周期化模式",
    phase: "准备期",
    duration_weeks: "4周为一个微循环组",
    daily_structure: ["第1-3周：逐渐增加负荷", "第4周：卸载/恢复，负荷约为峰值的60%"],
  },
  {
    id: "periodization_003", type: "periodization_rule",
    condition: "高级运动员或需要更强刺激时使用",
    name: "4:2加载模式",
    contraindications: ["初学者", "恢复能力差者"],
    rationale: "4周递增后接2周卸载，适合大负荷积累后的长恢复，进一步提升准备状态",
    phase: "准备期",
    duration_weeks: "6周为一个微循环组",
    daily_structure: ["第1-4周：递增负荷", "第5-6周：卸载/恢复"],
  },
  {
    id: "periodization_004", type: "periodization_rule",
    condition: "力量训练周期化，从解剖适应到最大力量再到爆发力转换",
    target: "力量/爆发力",
    name: "力量训练阶段序列",
    rationale: "先建立肌肉和结缔组织基础（解剖适应），再发展最大力量，最后转换为专项爆发力，符合阶段强化原则",
    phase: "解剖适应期 → 最大力量期 → 转换期 → 维持期",
    duration_weeks: "解剖适应4-6周；最大力量4-12周；转换4-6周；维持贯穿比赛期",
    weekly_frequency: "力量训练2-5次/周，根据阶段调整",
    daily_structure: ["解剖适应：高重复（8-12RM），低强度（40-65%1RM）", "最大力量：低重复（4-6RM），高强度（75-85%1RM）", "转换：爆发力动作（30-60%1RM快速完成）"],
  },
  {
    id: "periodization_005", type: "periodization_rule",
    condition: "年训练计划为单周期（monocycle），适用于有一项主要比赛的季节性运动",
    name: "单周期年计划结构",
    rationale: "单周期包括准备期（32周以上）、比赛期（10-15周）和过渡期（5周），适合速度力量型运动",
    phase: "准备期 → 比赛期 → 过渡期",
    duration_weeks: "52周",
    weekly_frequency: "准备期高频（8-15次/周），比赛期减少",
    daily_structure: ["准备期：高量低强度", "比赛期：低量高强度", "过渡期：积极休息"],
  },
  {
    id: "periodization_006", type: "periodization_rule",
    condition: "耐力型运动（如赛艇、长跑）的周期化强度分配",
    target: "耐力",
    name: "耐力运动强度分区",
    rationale: "通过强度分区（1-5区）精确控制有氧、无氧和比赛配速耐力，优化训练适应",
    phase: "准备期/比赛期",
    daily_structure: ["强度1区：速度耐力（>40桨频）", "强度2区：力量耐力（37-40桨频）", "强度3区：比赛配速（32-36桨频）", "强度4区：中等距离有氧（24-32桨频）", "强度5区：长距离有氧（<24桨频）"],
  },
  {
    id: "periodization_007", type: "periodization_rule",
    condition: "非线性周期化（灵活非线性）适用于多赛事、日程变化多的运动员",
    target: "力量/爆发力",
    name: "灵活非线性周期化 (Flexible Nonlinear Periodization)",
    difficulty: "中级-高级",
    rationale: "根据当日准备状态调整训练负荷（重、中、轻、爆发力日），避免单调疲劳，适应运动员生活节奏",
    phase: "全年适用",
    duration_weeks: "8-12周为一个大周期",
    weekly_frequency: "3-4次/周，根据计划轮换",
    daily_structure: ["重型日：1-3RM，5-7组", "中型日：8-10RM，2-4组", "轻型日：12-15RM，1-3组", "爆发力日：40-70%1RM，6-8组×3次"],
  },
  {
    id: "periodization_008", type: "periodization_rule",
    condition: "为年轻运动员设计的长期运动发展路径",
    target: "力量/爆发力/耐力/核心",
    name: "青少年长期运动发展",
    difficulty: "初级",
    contraindications: ["骨骼未成熟的儿童避免最大力量测试和最大负荷", "骨骺板未闭合避免过顶大重量"],
    sets_reps: "力量：1-2组，10-15次，50-70%1RM",
    rationale: "青少年应优先发展多元运动技能和基础力量，避免早期专项化，14-15岁后逐渐引入专项训练",
    phase: "一般准备期",
    duration_weeks: "多年",
    weekly_frequency: "2-3次/周",
    daily_structure: ["7岁前：身体自重和伙伴抗阻，游戏化", "8-10岁：增加轻负重，强调技术", "11-13岁：学习所有基本动作，渐进负荷", "14-15岁：进阶专项化"],
  },
  {
    id: "periodization_009", type: "periodization_rule",
    condition: "赛季中维持力量水平，避免过度疲劳",
    target: "力量/维持",
    name: "赛季中力量维持计划",
    rationale: "每周1-2次短时（30-40分钟）高强度力量训练即可维持力量水平，避免因长时间不训练而力量衰退",
    phase: "比赛期",
    duration_weeks: "整个赛季",
    weekly_frequency: "1-2次/周",
    daily_structure: ["每次30-40分钟", "2-4个多关节动作，每组1-3次，强度30-100%1RM", "避免训练至力竭"],
  },
];

// ================================================================
// Part 3: 弹跳专项诊断
// ================================================================
const KB_PART3: KBEntry[] = [
  {
    id: "dia_001", type: "weakness_diagnosis",
    condition: "进行反应性赤字测试：比较站立垂直跳高与从12-18英寸箱子跳下后的反弹跳高。若站立跳更高，且力量≥1.5倍体重",
    diagnosis: "反应力量较弱（plyometrically weak），更依赖力量而非弹性",
    target: "爆发力/反应力量",
    name: "反应性赤字测试（深度跳对比站立跳）",
    equipment: "测量尺、12-18英寸跳箱",
    difficulty: "初级/中级",
    contraindications: ["膝盖损伤", "踝关节不稳定"],
    sets_reps: "各尝试3-5次，取最佳",
    rationale: "比较力量型和弹跳型个体差异，指导训练重点",
  },
  {
    id: "dia_002", type: "weakness_diagnosis",
    condition: "无法深蹲至少1.5倍体重",
    diagnosis: "基础力量不足，需优先发展力量",
    target: "力量",
    name: "基础力量阈值筛查",
    equipment: "杠铃、深蹲架",
    difficulty: "初级",
    contraindications: ["下背部损伤", "膝盖损伤"],
    sets_reps: "测试1RM或估计1.5倍体重",
    rationale: "力量是垂直跳的基础，未达标前其他测试无效——此诊断优先于所有其他测试结果",
  },
  {
    id: "dia_003", type: "weakness_diagnosis",
    condition: "站立垂直跳与跑动垂直跳差距小于15%，且深蹲时明显屈膝俯身",
    diagnosis: "髋/膝伸肌主导（quad/hip dominant），踝关节贡献较少",
    target: "力量/踝关节爆发力",
    name: "关节贡献诊断（基于跳法差异）",
    equipment: "测量尺",
    difficulty: "中级",
    sets_reps: "分别测试站立跳、跑动跳、深度跳、单腿跑跳",
    rationale: "识别个人在髋、膝、踝的贡献比例，针对性训练",
  },
  {
    id: "dia_004", type: "weakness_diagnosis",
    condition: "深度跳（12-18英寸箱）表现显著低于站立跳，但力量达标（≥1.5倍体重深蹲）",
    diagnosis: "踝关节弹性/反应力量不足（ankle extensor weak）",
    target: "反应力量/踝关节刚度",
    name: "深度跳赤字诊断",
    equipment: "12-18英寸跳箱、测量尺",
    difficulty: "中级",
    contraindications: ["跟腱炎", "踝关节扭伤史"],
    sets_reps: "各尝试3-5次",
    rationale: "识别踝关节在垂直跳中的贡献缺陷",
  },
  {
    id: "exe_001", type: "exercise",
    condition: "适用于所有初级至中级训练者",
    target: "力量",
    name: "杠铃深蹲（平行或略低于平行）",
    equipment: "杠铃、深蹲架",
    difficulty: "初级/中级",
    contraindications: ["严重下背部损伤", "膝盖半月板撕裂", "医生禁止深蹲"],
    sets_reps: "3组×5次，逐渐加重",
    rationale: "增强下肢伸肌（髋、膝）力量，是垂直跳的基础力量动作",
    phase: "任何力量阶段",
    weekly_frequency: "2-3次/周",
    daily_structure: ["热身组（空杆5次）", "递增组至工作重量", "3组×5次"],
  },
  {
    id: "exe_002", type: "exercise",
    condition: "有一定力量基础（深蹲≥1.5倍体重）",
    target: "爆发力",
    name: "跳深（深度跳）",
    equipment: "跳箱（12-24英寸高，根据最佳高度确定）",
    difficulty: "中级/高级",
    contraindications: ["跟腱炎", "膝盖疼痛", "踝关节不稳定", "体重过大且力量不足"],
    sets_reps: "4组×5次，或6组×3次，每周1-2次",
    rationale: "利用离心过载增强踝关节和膝关节的弹性力量，提高反应力量",
    phase: "力量-速度阶段/峰值阶段",
    duration_weeks: "3-4",
    weekly_frequency: "1-2次/周",
    daily_structure: ["动态热身", "从低箱开始测试最佳高度", "4×5次，充分休息"],
  },
  {
    id: "exe_003", type: "exercise",
    condition: "适用于中级训练者，尤其需要提高发力速度",
    target: "爆发力/速度力量",
    name: "跳蹲（负重跳）",
    equipment: "杠铃或哑铃或负重背心",
    difficulty: "中级",
    contraindications: ["膝盖损伤", "下背部问题"],
    sets_reps: "3-5组×5次，负荷为深蹲1RM的15-30%",
    rationale: "模拟垂直跳的三关节伸展，在高速度下发展力量表达",
    phase: "速度力量阶段",
    weekly_frequency: "2次/周",
    daily_structure: ["动态热身", "4组×5次，每次落地后暂停重置"],
  },
  {
    id: "exe_004", type: "exercise",
    condition: "需要提高髋关节爆发力和上肢协调",
    target: "爆发力/力量速度",
    name: "悬垂高翻或悬垂抓举",
    equipment: "杠铃",
    difficulty: "高级（需技术指导）",
    contraindications: ["肩关节不稳定", "手腕损伤", "腰椎间盘突出"],
    sets_reps: "3-5组×1-3次，负荷80-90%",
    rationale: "训练三关节伸展和高速度发力，改善力量表达和上肢辅助",
    phase: "力量-速度/速度力量阶段",
    weekly_frequency: "1-2次/周",
    daily_structure: ["充分热身", "每组1-3次，重量递增"],
  },
  {
    id: "exe_005", type: "exercise",
    condition: "需要增强臀肌和后侧链力量",
    target: "力量",
    name: "罗马尼亚硬拉",
    equipment: "杠铃",
    difficulty: "中级",
    contraindications: ["下背部损伤", "腘绳肌撕裂史"],
    sets_reps: "2-3组×6-10次",
    rationale: "强化臀肌和腘绳肌，改善跳跃中的髋伸展",
    phase: "任何力量阶段",
    weekly_frequency: "1-2次/周",
    daily_structure: ["控制离心", "保持背部平直"],
  },
  {
    id: "exe_006", type: "exercise",
    condition: "需要增强臀肌且避免腰椎压力",
    target: "力量",
    name: "杠铃臀推",
    equipment: "杠铃、可调节凳",
    difficulty: "初级/中级",
    contraindications: ["急性髋关节损伤"],
    sets_reps: "2-3组×8-12次",
    rationale: "专项强化臀肌，提高髋伸展力量和跳跃效率",
    phase: "任何力量阶段",
    weekly_frequency: "1-2次/周",
    daily_structure: ["上背部靠凳", "杠铃放髋部", "顶峰收缩"],
  },
  {
    id: "exe_007", type: "exercise",
    condition: "需要增强小腿力量",
    target: "力量/踝关节刚度",
    name: "站姿提踵",
    equipment: "站姿提踵机或杠铃+垫块",
    difficulty: "初级",
    contraindications: ["跟腱炎急性期"],
    sets_reps: "2-3组×15-25次",
    rationale: "强化腓肠肌和比目鱼肌，提高踝关节力量和刚度",
    phase: "任何阶段",
    weekly_frequency: "2次/周",
    daily_structure: ["全幅度运动", "顶峰收缩"],
  },
  {
    id: "exe_008", type: "exercise",
    condition: "初级训练者，或作为辅助训练",
    target: "爆发力/反应力量",
    name: "膝胸跳（tuck jump）",
    equipment: "无",
    difficulty: "初级",
    contraindications: ["膝盖疼痛"],
    sets_reps: "3-4组×6-10次",
    rationale: "提高踝关节和膝关节的爆发力，改善协调性",
    phase: "速度力量阶段",
    weekly_frequency: "2-3次/周",
    daily_structure: ["连续跳跃", "膝盖抬高至胸部"],
  },
  {
    id: "exe_009", type: "exercise",
    condition: "需要提高单腿跳能力或短接触时间反应力量",
    target: "反应力量/爆发力",
    name: "低箱深度跳（短触地时间）",
    equipment: "6-12英寸跳箱",
    difficulty: "中级",
    contraindications: ["跟腱损伤", "踝关节不稳定"],
    sets_reps: "4组×5次，强调触地即起",
    rationale: "模拟单腿跳和短跑中的短接触时间，提高踝关节弹性",
    phase: "速度力量/峰值阶段",
    weekly_frequency: "1-2次/周",
    daily_structure: ["从低箱下落", "尽量少屈膝", "快速反弹"],
  },
  {
    id: "exe_010", type: "exercise",
    condition: "无器械或旅行中",
    target: "力量",
    name: "保加利亚分腿蹲（自重）",
    equipment: "长凳或台阶",
    difficulty: "初级/中级",
    contraindications: ["膝盖疼痛", "平衡严重问题"],
    sets_reps: "2-3组×10-15次/腿",
    rationale: "单侧下肢力量训练，接近跳跃模式",
    phase: "任何力量阶段",
    weekly_frequency: "2-3次/周",
    daily_structure: ["后脚垫高", "下蹲至膝轻触地"],
  },
  {
    id: "per_001", type: "periodization_rule",
    condition: "中级及以上训练者，需要系统提高垂直跳",
    target: "力量/爆发力/反应力量",
    name: "线性周期模型（4阶段）",
    difficulty: "中级/高级",
    rationale: "先建立基础体能和肥大，再到最大力量，最后转化为爆发力",
    phase: "适应期（4周）、肥大期（4周）、最大力量期（6周）、速度力量期（6周）",
    duration_weeks: "20周",
    weekly_frequency: "2-4次/周",
    daily_structure: ["适应期: 3组×12-15次", "肥大期: 3-4组×6-12次", "最大力量期: 5组×5次递减至6组×1次", "速度力量期: 跳蹲/增强式为主"],
  },
  {
    id: "per_002", type: "periodization_rule",
    condition: "已具备基本力量（深蹲≥1.5倍体重），希望同时发展多项素质",
    target: "力量/爆发力/反应力量",
    name: "共轭周期（同时训练）",
    difficulty: "中级",
    rationale: "同时刺激不同神经适应，适合非赛季长期发展",
    phase: "非赛季",
    duration_weeks: "持续",
    weekly_frequency: "2-3次/周",
    daily_structure: ["热身增强式（如踝跳、tuck jump）", "力量速度动作（跳蹲或高翻）", "力量主项（深蹲）", "辅助（臀推、提踵）"],
  },
  {
    id: "per_003", type: "periodization_rule",
    condition: "需要短期内峰值爆发力（如测试或比赛前）",
    target: "爆发力/力量表达",
    name: "峰值/激活后增强阶段",
    difficulty: "高级",
    contraindications: ["过度疲劳", "神经肌肉系统未恢复"],
    sets_reps: "低容量高强度，如8×1@85-90%深蹲，结合跳深",
    rationale: "利用激活后增强效应临时提升爆发力",
    phase: "峰值阶段（2-4周）",
    duration_weeks: "2-4周",
    weekly_frequency: "1-2次/周",
    daily_structure: ["深度跳+跑动跳交替", "85-90%深蹲单次", "轻跳蹲"],
  },
  {
    id: "per_004", type: "periodization_rule",
    condition: "训练遇到平台期或连续3次无进展",
    target: "恢复",
    name: "减载周",
    difficulty: "所有级别",
    sets_reps: "降低强度10-20%，或减少2/3容量",
    rationale: "消除疲劳，允许超量恢复——很多人的弹跳PR是在减载后的测试周创造的",
    phase: "减载周（每4-6周一次）",
    duration_weeks: "1周",
    weekly_frequency: "原频率的1/3-1/2",
    daily_structure: ["轻重量3×3@70-80%", "低容量增强式", "增加主动恢复"],
  },
];

// ================================================================
// Part 4: 基于力量/反应力量诊断的训练规则
// ================================================================
const KB_PART4: KBEntry[] = [
  {
    id: "diagnosis_001", type: "weakness_diagnosis",
    condition: "垂直跳跃（常规向下再向上）高度 ≥ 或 ≈ 反应性跳跃（从12英寸箱子跳下再跳起）高度",
    diagnosis: "反应性力量（拉长-缩短周期效率）不足，侧重于吸收和利用弹性/反射力的能力存在缺陷",
    target: "反应力量",
    rationale: "反应力量不足意味着无法有效利用肌肉肌腱的弹性势能，限制弹跳表现。",
  },
  {
    id: "diagnosis_002", type: "weakness_diagnosis",
    condition: "反应性跳跃高度比垂直跳跃（常规）高20%或更多，且随着箱子高度增加（>18英寸），跳跃高度持续增加",
    diagnosis: "反应性/弹性能力非常高效，基础力量相对不足。通过增加肌肉量和基础力量可以获得最大收益",
    target: "力量",
    rationale: "弹性能力优秀但力量基础薄弱，加强最大力量训练可获得更大弹跳提升。",
  },
  {
    id: "diagnosis_003", type: "weakness_diagnosis",
    condition: "最大深蹲重量 < 1.5倍体重",
    diagnosis: "基础力量是当前的主要限制因素，也是首要发展目标。此诊断优先于任何反应性测试结果",
    target: "力量",
    rationale: "基础力量不足是弹跳提升的最大瓶颈，必须优先发展力量。",
  },
  {
    id: "exercise_001_4", type: "exercise",
    condition: "当需要发展基础力量和最大力量时，特别是对于深蹲重量低于1.5倍体重的运动员",
    target: "力量",
    name: "杠铃后深蹲（全蹲）",
    equipment: "杠铃、深蹲架",
    difficulty: "初级",
    contraindications: ["如果在深蹲过程中或之后感到膝盖疼痛，应检查姿势并减轻重量", "下背部有伤病史者需谨慎，保持核心收紧和背部平直"],
    sets_reps: "根据训练阶段不同，从3组8-10次到4组4次不等",
    rationale: "深蹲训练了垂直跳中涉及的所有主要肌群（股四头肌、臀肌、腘绳肌）。提升的相对力量（力量/体重比）是决定垂直跳跃高度的最重要因素",
  },
  {
    id: "exercise_002_4", type: "exercise",
    condition: "当需要发展后侧链（臀肌、腘绳肌、下背）力量时",
    target: "力量",
    name: "硬拉",
    equipment: "杠铃",
    difficulty: "初级",
    contraindications: ["腰椎间盘突出或下背部有伤病史者需极度谨慎", "在增加重量前必须掌握保持背部平直的技术"],
    sets_reps: "根据训练阶段不同，从3组6-8次到4组4次不等",
    rationale: "无与伦比地发展后侧链肌肉，这些肌肉是爆发力的关键，且常是运动员的薄弱环节。强健的后侧链能防止伤病并提升运动表现",
  },
  {
    id: "exercise_003_4", type: "exercise",
    condition: "当需要提升发力率和爆发力时，特别是在力量基础已经建立之后",
    target: "爆发力",
    name: "负重蹲跳",
    equipment: "杠铃",
    difficulty: "中级",
    contraindications: ["膝盖、脚踝或下背部有伤病史者需谨慎", "落地时技术不当可能导致关节冲击伤害"],
    sets_reps: "3-4组，每组6-12次。负荷为最大深蹲重量的10%-30%",
    rationale: "结合了力量（阻力）和速度（爆发式动作），是发展「力量-速度」区域爆发力的理想练习，能将最大力量转化为爆发力",
  },
  {
    id: "exercise_004_4", type: "exercise",
    condition: "当需要发展反应力量（伸缩循环）和吸收落地冲击力的能力时，特别是在建立了足够的力量基础（深蹲≥1.5倍体重）之后",
    target: "反应力量",
    name: "跳深（从箱子跳下再跳起）",
    equipment: "稳定的跳箱或平台",
    difficulty: "高级",
    contraindications: ["初学者或深蹲重量低于1.5倍体重者禁止进行", "落地时脚跟着地表明箱子过高，应立即停止", "落地声音沉重、技术变形表明负荷过大", "每周不超过2-3次，每组不超过10次，总次数不超过40次"],
    sets_reps: "2-4组，每组5-10次。箱子高度通常在18-28英寸之间，应保证落地时脚后跟不触地",
    rationale: "这是最经典的增强式训练，通过快速离心拉伸肌肉和肌腱，储存并释放弹性能量，从而产生比纯自主收缩更强大的向心收缩",
  },
  {
    id: "exercise_005_4", type: "exercise",
    condition: "当需要专门提升吸收高冲击力的能力（离心力量）和肌肉/肌腱的刚度时",
    target: "核心",
    name: "冲击跳/下落稳定（从高处跳下并「粘住」落地）",
    equipment: "稳定的跳箱或平台",
    difficulty: "高级",
    contraindications: ["初学者或深蹲重量低于1.5倍体重者禁止进行", "落地时脚跟着地或发出沉重的「砰」声表明负荷过大", "对关节（尤其是膝关节和脊柱）的压力极大"],
    sets_reps: "1-5组，每组3-5次。箱子高度可高于跳深，最高可达50英寸，但必须确保能完美地吸收冲击",
    rationale: "专注于吸收离心（落地）阶段的能量。提升吸收高冲击力的能力是发展高水平反应力量的前提，同时也能强化肌腱，预防伤病",
  },
  {
    id: "rule_001", type: "periodization_rule",
    condition: "对于大多数以提升纵跳为主要目标的运动员，特别是那些还参与其他需要速度/弹跳的运动（如篮球、排球）的运动员",
    target: "力量",
    rationale: "由于运动本身（如打篮球）已经提供了充足的速度和反应力量刺激，力量房内的训练重点应是发展最大力量（80%-100%强度），这是爆发力的基础。而通过跳、跑等训练发展速度成分效率更高",
    phase: "一般准备期",
    duration_weeks: "4-8周",
    weekly_frequency: "2-3次/周",
    daily_structure: ["深蹲/硬拉等最大力量训练（80%-100%强度）", "少量爆发力或反应力量训练以保持或衔接"],
  },
  {
    id: "rule_002", type: "periodization_rule",
    condition: "运动员的测试结果显示其反应力量（弹性能利用率）是其优势，而最大力量是短板（例如，在跳深测试中成绩远超原地纵跳）",
    diagnosis: "反应力量高效，但基础力量不足",
    target: "力量",
    rationale: "运动员在利用肌腱弹性能方面有天赋，但受限于基础力量水平。优先发展最大力量可以创建一个更大的「力量库」，供其高效的反应系统利用，从而实现跳跃能力的突破",
    phase: "力量优先阶段",
    duration_weeks: "8-16周",
    weekly_frequency: "2次力量训练 + 1次低容量增强式训练/周",
    daily_structure: ["主要进行大重量、低次数的深蹲、硬拉等力量训练", "辅助以少量、低强度的增强式训练以维持反应能力"],
  },
  {
    id: "rule_003", type: "periodization_rule",
    condition: "运动员的测试结果显示其最大力量相对充足（深蹲≥1.5倍体重），但反应力量/弹性是其短板（例如，原地纵跳成绩接近或优于跳深成绩）",
    diagnosis: "力量充足，但反应力量不足",
    target: "反应力量",
    rationale: "运动员拥有足够的力量「原料」，但无法快速有效地将其转化为爆发力，尤其是在利用伸缩循环时。需要专门进行增强式训练来教会神经系统和肌肉-肌腱系统如何更高效地储存和释放能量",
    phase: "反应力量优先阶段",
    duration_weeks: "8-16周",
    weekly_frequency: "2次/周（包含力量和增强式训练的组合）",
    daily_structure: ["大量跳箱、跳深、多级跳等增强式训练", "配合中等强度的快速力量训练（如负重蹲跳）以发展发力率"],
  },
  {
    id: "rule_004", type: "periodization_rule",
    condition: "对于所有级别的运动员，在进行高强度增强式训练（如跳深、冲击跳）后",
    target: "恢复",
    rationale: "高强度增强式训练对中枢神经系统（CNS）的消耗极大，其恢复时间比肌肉系统长约5倍。如果不充分休息，会导致CNS疲劳，表现为反应变慢、爆发力下降",
    phase: "训练后恢复",
    duration_weeks: "始终",
    daily_structure: ["在两次高强度增强式训练之间安排至少48-72小时的休息", "避免在赛季中或身体疲劳时进行大容量高强度增强式训练"],
  },
  {
    id: "rule_005", type: "periodization_rule",
    condition: "对于任何训练方法，特别是非常有效的深度跳跃，应避免常年连续使用",
    name: "深度跳跃的周期化使用",
    difficulty: "高级",
    rationale: "任何训练方法，无论多么有效，随着时间的推移都会失去其效力。使用短周期（如几周）的深度跳跃可以产生强烈的刺激，获得显著的爆发力提升，而长期连续使用则会导致适应和收益递减",
    phase: "专项准备期/赛前期",
    duration_weeks: "2-4周",
    weekly_frequency: "1-2次/周",
    daily_structure: ["在年度训练计划中，穿插为期2-4周的深度跳跃集中训练块", "其他时间以其他类型的跳跃、力量或速度训练为主"],
  },
];

// ================================================================
// 合并全部知识库
// ================================================================

// ================================================================
// Part 5: Supertraining (Verkhoshansky/Siff) 知识
// ================================================================
const KB_PART5: KBEntry[] = [
  {
    id: "supertraining_diag_001", type: "weakness_diagnosis",
    condition: "在给定动作中，最大自愿力量（如深蹲1RM）与绝对力量（通过电刺激或强反射诱发的最大力量）之间的差距较大，且运动时间短、外部阻力小",
    diagnosis: "力量缺陷较大，表明神经肌肉系统未能充分激活高阈值运动单位，优先需要发展速度-力量（爆发力）和发力率",
    target: "爆发力",
    rationale: "力量缺陷大时，通过最大或近最大神经肌肉刺激（如举重、增强式训练）能更有效地提高速度-力量和发力率；若缺陷小，则需优先通过次最大负荷训练诱导肌肉肥大",
  },
  {
    id: "supertraining_diag_002", type: "weakness_diagnosis",
    condition: "最大动态力量（Fmax）与绝对力量（So）的差值随外部阻力减小而增大，且初始发力阶段（起始力量）与绝对力量相关性低",
    diagnosis: "绝对力量不是爆发力表现的决定因素，尤其是轻负荷快速动作。训练需侧重起始力量和加速力量，而非单纯最大力量",
    target: "爆发力",
    rationale: "绝对力量与高速轻负荷运动表现呈负相关或弱相关；发力率（RFD）和反应能力是决定快速动作效能的关键",
  },
  {
    id: "supertraining_exercise_001", type: "exercise",
    condition: "适用于需要发展下肢爆发力、反应力量和弹性能利用能力的中高级运动员，且已具备足够力量基础（如深蹲≥1.5倍体重）",
    target: "反应力量",
    name: "跳深（深度跳跃）",
    equipment: "稳定的跳箱（高度18-28英寸）",
    difficulty: "高级",
    contraindications: ["初学者或深蹲重量低于1.5倍体重者不应进行","落地时脚跟触地表明箱子过高，应立即停止","膝关节、踝关节或下背部有伤病史者禁用","每周不应超过2-3次，单次训练总次数不超过40次","不得在疲劳状态下进行"],
    sets_reps: "4组×5次，或3组×8次，组间休息2-3分钟。总跳跃次数：高级运动员≤40次，中低水平≤15-24次",
    rationale: "跳深利用快速离心拉伸储存弹性能，并通过强直牵张反射增强向心收缩力量，是发展反应力量最有效的训练方法之一",
  },
  {
    id: "supertraining_exercise_002", type: "exercise",
    condition: "用于发展下肢最大力量和基础力量，尤其适用于初学者或力量水平较低的运动员",
    target: "力量",
    name: "杠铃后深蹲（全蹲）",
    equipment: "杠铃、深蹲架",
    difficulty: "初级",
    contraindications: ["腰椎间盘突出或严重下背痛者应在专业指导下进行","膝关节损伤急性期禁用","姿势不正确时可能增加腰椎和膝关节压力"],
    sets_reps: "初学者：3组×8-10次，负荷为50-70% 1RM；进阶：4组×4-6次，负荷80-90% 1RM。组间休息2-3分钟",
    rationale: "全范围深蹲能全面刺激股四头肌、臀肌、腘绳肌及核心肌群，是提升下肢最大力量和相对力量的基础动作，对纵跳高度有直接正向转移",
  },
  {
    id: "supertraining_exercise_003", type: "exercise",
    condition: "适用于发展后侧链（臀肌、腘绳肌、竖脊肌）力量，以及提高髋关节伸展能力",
    target: "力量",
    name: "硬拉",
    equipment: "杠铃",
    difficulty: "初级",
    contraindications: ["急性腰椎损伤或椎间盘突出者禁用","技术不当会增加腰椎剪切力"],
    sets_reps: "3-5组×5-8次，负荷70-85% 1RM，组间休息2-3分钟",
    rationale: "硬拉是发展后侧链力量最有效的动作之一，强健的臀肌和腘绳肌对于跳跃和冲刺中的力量传递至关重要",
  },
  {
    id: "supertraining_exercise_004", type: "exercise",
    condition: "用于提升爆发力和力量-速度，尤其适合在力量基础建立后作为辅助训练",
    target: "爆发力",
    name: "高翻（Clean）",
    equipment: "杠铃",
    difficulty: "中级",
    contraindications: ["手腕、肘部或肩部有伤病史者需谨慎","初学者应在教练指导下学习动作技术"],
    sets_reps: "5组×3-5次，负荷70-85% 1RM，组间休息2-3分钟",
    rationale: "高翻是典型的爆发力训练动作，要求快速发力、协调全身，能高效提升发力率和功率输出，对跳跃和冲刺有显著转移效果",
  },
  {
    id: "supertraining_rule_001", type: "periodization_rule",
    condition: "适用于高水平运动员（尤其是爆发力项目）的年度训练规划，希望突破平台并利用长期延迟训练效应（LDTE）",
    target: "力量/爆发力",
    name: "集中负荷法（Concentrated Loading）",
    difficulty: "高级",
    contraindications: ["不适用于初学者或低水平运动员","过度集中负荷可能导致过度训练、力量-速度下降和技术变形","必须在集中负荷后安排充足的恢复阶段以诱发LDTE"],
    rationale: "将高强度、大容量的单方向训练（如力量）集中在4-8周内，可造成持久的内稳态扰动，随后在减量阶段产生超量补偿和长期延迟训练效应，显著提升专项能力",
    phase: "专项准备期",
    duration_weeks: "4-8周",
    weekly_frequency: "3-5次/周（取决于专项）",
    daily_structure: ["集中力量训练为主","技术训练以低强度保持","结束后安排减量恢复期"],
  },
  {
    id: "supertraining_rule_002", type: "periodization_rule",
    condition: "适用于需要同时发展多种运动能力（力量、速度、耐力）但避免负迁移的高水平运动员",
    target: "综合性",
    name: "共轭顺序系统（Conjugate Sequence System）",
    difficulty: "高级",
    rationale: "通过按顺序引入训练效果逐渐增强的手段，使前一阶段的适应性为后一阶段创造有利条件，从而获得累加的正向训练效果，避免同时进行多种训练产生的干扰",
    phase: "年度大周期",
    duration_weeks: "12-16周",
    weekly_frequency: "依专项而定",
    daily_structure: ["阶段1：基础耐力","阶段2：集中力量训练","阶段3：速度-力量及技术强化（利用LDTE）","阶段4：比赛前减量"],
  },
  {
    id: "supertraining_rule_003", type: "periodization_rule",
    condition: "适用于需要爆发力的运动项目（如跳跃、投掷、短跑）的中高水平运动员，在准备期采用",
    target: "反应力量",
    name: "增强式训练周期化安排",
    equipment: "跳箱、障碍物",
    difficulty: "中级",
    contraindications: ["未建立足够力量基础（深蹲<1.5倍体重）者禁用深度跳","关节损伤或疼痛时禁用"],
    rationale: "增强式训练应根据运动强度和恢复能力进行周期化：初期使用低强度、高重复训练（如跳绳、小跳），后期使用高强度、低重复训练（如深度跳、冲击跳），并安排足够恢复时间以避免神经系统疲劳",
    phase: "准备期后期及赛前期",
    duration_weeks: "4-6周",
    weekly_frequency: "1-2次/周（高强度）或2-3次/周（低强度）",
    daily_structure: ["热身与动态拉伸","低强度反应练习（如踝跳、侧向跳）","中等强度增强式（如箱跳、跨步跳）","高强度深度跳（≤40次总落地）","整理与放松"],
  },
];

// 将 Part 5 加入合并数组
const ALL_PARTS = [...KB_PART1, ...KB_PART2, ...KB_PART3, ...KB_PART4, ...KB_PART5];

export const USER_KNOWLEDGE_BASE: KBEntry[] = [
  ...KB_PART1,
  ...KB_PART2,
  ...KB_PART3,
  ...KB_PART4,
];

/** 将用户知识库格式化为 AI Prompt 可用的文本 */
export function formatUserKnowledgeBase(): string {
  const parts: string[] = ["## 权威知识库（用户提供）\n"];

  // Weakness diagnoses
  const diagnoses = USER_KNOWLEDGE_BASE.filter(e => e.type === "weakness_diagnosis");
  if (diagnoses.length > 0) {
    parts.push("\n### 短板诊断规则");
    for (const d of diagnoses) {
      parts.push(`- **${d.id}**: ${d.condition}`);
      parts.push(`  诊断: ${d.diagnosis || "无"}`);
      if (d.target) parts.push(`  目标方向: ${d.target}`);
      if (d.rationale) parts.push(`  依据: ${d.rationale}`);
      if (d.contraindications?.length) parts.push(`  禁忌: ${d.contraindications.filter(Boolean).join("；")}`);
    }
  }

  // Exercises
  const exercises = USER_KNOWLEDGE_BASE.filter(e => e.type === "exercise");
  if (exercises.length > 0) {
    parts.push("\n### 训练动作库");
    for (const ex of exercises) {
      parts.push(`- **${ex.name || ex.id}** (${ex.difficulty || "未指定"})`);
      parts.push(`  条件: ${ex.condition}`);
      if (ex.equipment) parts.push(`  器材: ${ex.equipment}`);
      if (ex.target) parts.push(`  目标: ${ex.target}`);
      if (ex.sets_reps) parts.push(`  组次: ${ex.sets_reps}`);
      if (ex.rationale) parts.push(`  依据: ${ex.rationale}`);
      if (ex.phase) parts.push(`  阶段: ${ex.phase}`);
      if (ex.weekly_frequency) parts.push(`  频率: ${ex.weekly_frequency}`);
      if (ex.contraindications?.length) parts.push(`  ⚠️ 禁忌: ${ex.contraindications.filter(Boolean).join("；")}`);
      if (ex.daily_structure?.length) parts.push(`  日结构: ${ex.daily_structure.filter(Boolean).join(" | ")}`);
    }
  }

  // Periodization rules
  const rules = USER_KNOWLEDGE_BASE.filter(e => e.type === "periodization_rule");
  if (rules.length > 0) {
    parts.push("\n### 周期化训练规则");
    for (const r of rules) {
      parts.push(`- **${r.name || r.id}**: ${r.condition}`);
      if (r.diagnosis) parts.push(`  诊断: ${r.diagnosis}`);
      if (r.target) parts.push(`  目标: ${r.target}`);
      if (r.rationale) parts.push(`  依据: ${r.rationale}`);
      if (r.phase) parts.push(`  阶段: ${r.phase}`);
      if (r.duration_weeks) parts.push(`  时长: ${r.duration_weeks}`);
      if (r.weekly_frequency) parts.push(`  频率: ${r.weekly_frequency}`);
      if (r.contraindications?.length) parts.push(`  ⚠️ 禁忌: ${r.contraindications.filter(Boolean).join("；")}`);
      if (r.daily_structure?.length) parts.push(`  日结构: ${r.daily_structure.filter(Boolean).join(" | ")}`);
    }
  }

  return parts.join("\n");
}
